repo_name: Deep Python Client
repo_url: https://github.com/intergral/deep-python-client

site_dir: _site

site_name: Deep Python Client Docs
site_url: https://intergral.github.io/deep-python-client/

copyright: Intergral GmbH 2023

extra_css:
  - styles.css

theme:
  logo: https://github.com/intergral/deep/blob/master/docs/docs/images/logo/icon.png?raw=true
  favicon: https://github.com/intergral/deep/blob/master/docs/docs/images/logo/icon.svg?raw=true
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Config: config/config.md
  - Auth:
      - Providers: auth/providers.md

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

